version: '2'

linters:
  default: all
  enable:
    - govet
    - errcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      
formatters:
  enable:
    - gofmt
      
output:
  formats:
    text:
      path: stderr
  sort-order:
    - linter
    - severity
    - file
  show-stats: false

run:
  timeout: 10m
  tests: false
  allow-parallel-runners: true
  go: '1.24'

severity:
  default: error