###

POST http://localhost:8000/api/v1/categories
Authorization: Bearer {access_token}
Content-Type: application/json

{
  "name": "Электроника"
}

###

POST http://localhost:8000/api/v1/products
Authorization: Bearer {access_token}
Content-Type: application/json

{
  "title": "Phone",
  "price": 40000,
  "quantity": 6,
  "category_id": 1,
  "status": "available"
}

###

GET http://localhost:8000/api/v1/products
Authorization: Bearer {access_token}

###
GET http://localhost:8000/api/v1/products/1
Authorization: Bearer {access_token}


###

PUT http://localhost:8000/api/v1/products/1
Authorization: Bearer {access_token}
Content-Type: application/json

{
  "title": "Новый заголовок 2"
}

###

PUT http://localhost:8000/api/v1/products/1/status
Authorization: Bearer {access_token}
Content-Type: application/json

{
  "status": "снова в продаже"
}

###

POST http://localhost:8000/api/v1/products/1/image
Authorization: Bearer {access_token}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg

< test.jpg
--WebAppBoundary--

###

GET http://localhost:8000/api/v1/products/1/image
Authorization: Bearer {access_token}