@host = localhost
@port = 8000
@version = api/v1
@baseUrl = {{host}}:{{port}}/{{version}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiYXVkIjpbImFkbWluIl0sImV4cCI6MTc0ODQ0MDk3MSwiaWF0IjoxNzQ4NDQwMDcxLCJqdGkiOiI1MGQyYzBhNC1jNzFiLTRkNzQtODg5ZS1kY2NhYzExYTY3ODMifQ.tF9ICnh75C51y2bVnzEm-cNY4-Tkkhct1wzkqmKlcnc

###

POST http://{{baseUrl}}/categories/ HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "electronics"
}

###

GET http://{{baseUrl}}/categories/ HTTP/1.1
Authorization: Bearer {{accessToken}}


###

POST http://{{baseUrl}}/products/ HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "phone",
  "price": 40000,
  "quantity": 6,
  "category_id": 1,
  "status": "available"
}

###

GET http://{{baseUrl}}/products/ HTTP/1.1
Authorization: Bearer {{accessToken}}

###

GET http://{{baseUrl}}/products/1 HTTP/1.1
Authorization: Bearer {{accessToken}}

###

PUT http://{{baseUrl}}/products/1 HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "watch"
}

###

PUT http://{{baseUrl}}/products/1/status HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "available"
}

###

POST http://{{baseUrl}}/products/1/image HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Type: image/jpeg
Content-Disposition: form-data; name="image"; filename="test.jpg"

< test.jpg
--WebAppBoundary--

###

GET http://{{baseUrl}}/products/1/image HTTP/1.1
Authorization: Bearer {{accessToken}}