@host = localhost
@port = 8080
@version = api/v1
@baseUrl = {{host}}:{{port}}/{{version}}
@refreshToken = REFRESH_TOKEN_HERE

###

GET http://{{baseUrl}}/health HTTP/1.1

###

POST http://{{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "john",
    "password": "12345678"
}

###

POST http://{{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "john",
    "password": "12345678"
}

###

POST http://{{baseUrl}}/auth/refresh HTTP/1.1
Content-Type: application/json

{
    "refresh_token": {{refreshToken}}
}