// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockRepository
func (_mock *MockRepository) Check(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockRepository_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - context1
func (_e *MockRepository_Expecter) Check(context1 interface{}) *MockRepository_Check_Call {
	return &MockRepository_Check_Call{Call: _e.mock.On("Check", context1)}
}

func (_c *MockRepository_Check_Call) Run(run func(context1 context.Context)) *MockRepository_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_Check_Call) Return(err error) *MockRepository_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Check_Call) RunAndReturn(run func(context1 context.Context) error) *MockRepository_Check_Call {
	_c.Call.Return(run)
	return _c
}
