name: linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu=latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache-dependency-path: go.sum
        
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
      
      - name: Update dependencies
        run: |
          go mod tidy
      
      - name: Run golangci-lint
        run:  |
          golangci-lint run ./...