name: testing
on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: gotest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup=go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache-dependency-path: go.sum
        
      - name: Update dependencies
        runs: |
          go mod tidy

      - name: Run tests 
        run: |
          go test ./...
